import { useState } from "react";
import Head from "next/head";
import { Burger } from "@mantine/core";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [opened, setOpened] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Burger opened={opened} onClick={() => setOpened((open) => !open)} />

        <p className={styles.description}>
          A bug where the burger menu above 👆🏼 loses styles after refreshing in
          next.js dev mode.
        </p>
      </main>
    </div>
  );
}
